name: rob_monit_org_growth
channels:
  - defaults
  - radiomics
  - simpleitk
  - conda-forge
dependencies:
  - ipykernel=6.15
  - ipython=8.4.0
  - jupyter=1.0.0
  - matplotlib=3.6.0
  - numpy=1.23.3
  - pandas=1.5
  - pillow=9.2.0
  - pyradiomics=v3.0.1
  - python=3.9.0
  - seaborn=0.12.0
  - scikit-learn=1.3.0
  - simpleitk=2.1
  - statannot


